# Generated by Django 3.0.4 on 2020-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20200421_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
    ]
