# Generated by Django 3.0.4 on 2020-04-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Symbol', verbose_name='pair'),
        ),
    ]
